dist: focal
sude: required
language: generic

services:
  - docker

before_install:
    - docker build -t abenakn/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true abenakn/react-test npm test 

after_success:
    - docker build -t abenakn/multi-client ./client
    - docker build -t abenakn/multi-nginx ./nginx
    - docker build -t abenakn/multi-server ./server
    - docker build -t abenakn/multi-worker ./worker
# Login to docker CLI
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  
# Push images to docker hub
    - docker push abenakn/multi-client
    - docker push abenakn/multi-nginx
    - docker push abenakn/multi-server
    - docker push abenakn/multi-worker

#Deploy to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-543392323903
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
   