entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true

http:
  routers:
    api:
      rule: "PathPrefix(`/api`) || PathPrefix(`/ws`)"
      entryPoints:
        - web
      service: api
      middlewares:
        - strip-api

    client:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: client

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:5000"

    client:
      loadBalancer:
        servers:
          - url: "http://client:3000"
